name: Build Driver
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Restore NuGet packages
        run: nuget restore minidrv.vcxproj

      - name: Build project
        run: msbuild minidrv.vcxproj /p:Platform=x64 /p:Configuration=Release

      - name: Upload sys artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-sys
          path: x64\Release\minidrv.sys
